export const slackPayloadFormatExpected = {
  empty: JSON.stringify(
    {
      channel: "<your-channel>",
      color: "<your-color>",
      attachments: [
        {
          blocks: [
            { type: "header", text: { type: "plain_text", text: "<your-title>" } },
            {
              type: "context",
              elements: [
                { type: "mrkdwn", text: "📦 *0 commits* included" },
                { type: "mrkdwn", text: "✅ *0 stories* delivered" },
                { type: "mrkdwn", text: "🚨 *0 stories* needing attention" },
                { type: "mrkdwn", text: "🚧 *0 stories* unfinished" },
                { type: "mrkdwn", text: "🛠️ *0 chores* included" },
              ],
            },
            { type: "context", elements: [{ type: "mrkdwn", text: "View details on GitHub: <your-release-url>" }] },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "✅ *Accepted Stories (0)*" } },
            { type: "section", text: { type: "plain_text", text: "No stories." } },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🚨 *Needs Attention (0)*" } },
            { type: "section", text: { type: "plain_text", text: "No stories." } },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🚧 *Not Finished Stories (0)*" } },
            { type: "section", text: { type: "plain_text", text: "No stories." } },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🛠️ *Chores (0)*" } },
            { type: "section", text: { type: "plain_text", text: "No chores." } },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🔍 *Non-story Commits (0)*" } },
            { type: "section", text: { type: "plain_text", text: "No commits." } },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            {
              type: "context",
              elements: [
                { type: "mrkdwn", text: "_Generated by <https://github.com/Bekind-Labs/tb-changelog|tb-changelog>_" },
              ],
            },
          ],
        },
      ],
    },
    null,
    2,
  ),
  full: JSON.stringify(
    {
      channel: "<your-channel>",
      color: "<your-color>",
      attachments: [
        {
          blocks: [
            { type: "header", text: { type: "plain_text", text: "<your-title>" } },
            {
              type: "context",
              elements: [
                { type: "mrkdwn", text: "📦 *8 commits* included" },
                { type: "mrkdwn", text: "✅ *2 stories* delivered" },
                { type: "mrkdwn", text: "🚨 *1 stories* needing attention" },
                { type: "mrkdwn", text: "🚧 *1 stories* unfinished" },
                { type: "mrkdwn", text: "🛠️ *2 chores* included" },
              ],
            },
            { type: "context", elements: [{ type: "mrkdwn", text: "View details on GitHub: <your-release-url>" }] },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "✅ *Accepted Stories (2)*" } },
            {
              type: "rich_text",
              elements: [
                {
                  type: "rich_text_list",
                  style: "bullet",
                  indent: 0,
                  border: 0,
                  elements: [
                    {
                      type: "rich_text_section",
                      elements: [
                        { type: "text", text: "🧩 " },
                        {
                          type: "link",
                          url: "https://trackerboot.com/projects/90001111/stories/111",
                          text: "Feature story 1",
                        },
                      ],
                    },
                    {
                      type: "rich_text_section",
                      elements: [
                        { type: "text", text: "🎨 " },
                        {
                          type: "link",
                          url: "https://trackerboot.com/projects/90001111/stories/222",
                          text: "Design story 1",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🚨 *Needs Attention (1)*" } },
            {
              type: "context",
              elements: [
                {
                  type: "mrkdwn",
                  text: "These stories show *mismatches*: finish commits and story status do not align.",
                },
              ],
            },
            {
              type: "rich_text",
              elements: [
                {
                  type: "rich_text_list",
                  style: "bullet",
                  indent: 0,
                  border: 0,
                  elements: [
                    {
                      type: "rich_text_section",
                      elements: [
                        { type: "text", text: "🎨 " },
                        {
                          type: "link",
                          url: "https://trackerboot.com/projects/90001111/stories/333",
                          text: "Design story 2",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🚧 *Not Finished Stories (1)*" } },
            {
              type: "context",
              elements: [
                { type: "mrkdwn", text: "These stories are *not completed*: no finish commit and not accepted." },
              ],
            },
            {
              type: "rich_text",
              elements: [
                {
                  type: "rich_text_list",
                  style: "bullet",
                  indent: 0,
                  border: 0,
                  elements: [
                    {
                      type: "rich_text_section",
                      elements: [
                        { type: "text", text: "🦋 " },
                        {
                          type: "link",
                          url: "https://trackerboot.com/projects/90001111/stories/444",
                          text: "Bug story 1",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🛠️ *Chores (2)*" } },
            {
              type: "rich_text",
              elements: [
                {
                  type: "rich_text_list",
                  style: "bullet",
                  indent: 0,
                  border: 0,
                  elements: [
                    {
                      type: "rich_text_section",
                      elements: [
                        {
                          type: "link",
                          url: "https://trackerboot.com/projects/90001111/stories/555",
                          text: "Chore story 1",
                        },
                      ],
                    },
                    {
                      type: "rich_text_section",
                      elements: [
                        {
                          type: "link",
                          url: "https://trackerboot.com/projects/90001111/stories/666",
                          text: "Chore story 2",
                        },
                        { type: "text", text: " (Not finished)" },
                      ],
                    },
                  ],
                },
              ],
            },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            { type: "section", text: { type: "mrkdwn", text: "🔍 *Non-story Commits (1)*" } },
            {
              type: "rich_text",
              elements: [
                {
                  type: "rich_text_list",
                  style: "bullet",
                  indent: 0,
                  border: 0,
                  elements: [{ type: "rich_text_section", elements: [{ type: "text", text: "Non-story commit" }] }],
                },
              ],
            },
            { type: "section", text: { type: "plain_text", text: " " } },
            { type: "divider" },
            {
              type: "context",
              elements: [
                { type: "mrkdwn", text: "_Generated by <https://github.com/Bekind-Labs/tb-changelog|tb-changelog>_" },
              ],
            },
          ],
        },
      ],
    },
    null,
    2,
  ),
};
