import type { GitCommit, Story } from "../../types";
import type { OutputGeneratorParameters } from "../generate-output";
import { generateUrl, getStoryIcon } from "./utils";

const SPACER = "<br />";

export const generateGithubMarkdown = (
  {
    projectId,
    categorizedStories: {
      acceptedStories,
      needsAttentionStories,
      notFinishedStories,
      chores,
      nonStoryCommits,
      totalCommits,
    },
    includeSignature,
  }: OutputGeneratorParameters,
  isLight: boolean,
): string => {
  return `
> [!NOTE]
> 📦 ${totalCommits} commits included, ✅ ${acceptedStories.length} stories delivered,
> 🚨 ${needsAttentionStories.length} stories needing attention, 🚧 ${notFinishedStories.length} stories unfinished, 🛠️ ${chores.length} chores included

${generateFromStories({
  projectId,
  title: `✅ Accepted Stories`,
  stories: acceptedStories,
  isLight,
})}

${generateFromStories({
  projectId,
  title: `🚨 Needs Attention`,
  stories: needsAttentionStories,
  warningText: `
> [!WARNING]
> These stories show **mismatches**: finish commits and stort status do not align.  
> Please review and resolve before release.
`.trim(),
  isLight,
})}

${generateFromStories({
  projectId,
  title: `🚧 Not Finished Stories`,
  stories: notFinishedStories,
  warningText: `
> [!CAUTION]
> These stories are **not completed**: no finish commit and not accepted.  
> Please confirm whether they can be released as-is.
`.trim(),
  isLight,
})}

${generateFromStories({
  projectId,
  title: `🛠️ Chores`,
  stories: chores,
  isLight,
})}

## 🔍 Non-story Commits (${nonStoryCommits.length})
${nonStoryCommits.length ? generateCommitList(nonStoryCommits) : "No commits."}

${includeSignature ? "---\n*Generated by [tb-changelog](https://github.com/Bekind-Labs/tb-changelog)*" : ""}
  `.trim();
};

const generateFromStories = ({
  projectId,
  title,
  stories,
  warningText = "",
  isLight,
}: {
  projectId: string;
  title: string;
  stories: Story[];
  warningText?: string;
  isLight: boolean;
}): string => {
  let text = `## ${title} (${stories.length})\n`;

  if (stories.length === 0) {
    text += "No stories.";
  } else {
    if (warningText) {
      text += `${warningText}\n`;
    }

    text += stories
      .map((story) => {
        const header = createTitle({ projectId, story, isLight });
        const commitList = isLight ? "" : `\n${generateCommitList(story.commits)}`;
        return `${header}${commitList}`;
      })
      .join("\n");
  }

  return `${text}\n\n${SPACER}`;
};

const createTitle = ({ projectId, story, isLight }: { projectId: string; story: Story; isLight: boolean }) => {
  const prefix = isLight ? "-" : "####";
  const icon = story.storyType !== "Chore" ? `${getStoryIcon(story.storyType)} ` : "";
  const url = generateUrl(projectId, story.id);
  const notFinishedForChore = story.storyType === "Chore" && story.status !== "Accepted" ? " (Not finished)" : "";

  return `${prefix} ${icon}[${story.title}](${url})${notFinishedForChore}`;
};

const generateCommitList = (commits: GitCommit[]): string => {
  return commits.map((commit) => `- ${commit.message} ${commit.shortHash}`).join("\n");
};
